_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: olivero
defaults:
  sender: php_mail
  formatter: php_mail
modules:
  sendgrid_integration:
    none:
      sender: sendgrid_integration
      formatter: sendgrid_integration
  webform:
    none:
      sender: php_mail
      formatter: php_mail
